version: 2.1

jobs:
  # for arm, we only have ubuntu, so we use that everywhere
  build:
    parameters:
      rclass:
        description: resource_class to use
        type: string
    machine:
      image: ubuntu-2004:202101-01
    resource_class: << parameters.rclass >>
    working_directory: /tmp/workspace
    steps:
      - run:
          name: Install dependencies (on master, install varnish from source)
          command: |
            export DEBIAN_FRONTEND=noninteractive
            export DEBCONF_NONINTERACTIVE_SEEN=true
            sudo -E -- apt-get update
            sudo -E -- apt-get install -y \
                automake \
                git \
                libjemalloc-dev \
                libedit-dev \
                libtool \
                libunwind-dev \
                make \
                libpcre3-dev \
                python3-docutils \
                python3 \
                python3-sphinx
            git clone https://github.com/varnishcache/varnish-cache.git /tmp/varnish-cache
            cd /tmp/varnish-cache
            ./autogen.des
            if [ "arm.medium" = "<< parameters.rclass >>" ]; then
                ./configure --libdir=/usr/lib/aarch64-linux-gnu/
            else
                ./configure --libdir=/usr/lib/x86_64-linux-gnu/
            fi
            make -j 8
            sudo make install
      - checkout
      - run:
          name: Build and test
          command: |
            ./bootstrap
            ./configure
            make -k
            make check -j4 VERBOSE=1
            sudo make install


# two workflows, identical but for their triggers (commit/scheduled)
workflows:
  version: 2
  # run the build job for all commits
  commit: &jobs
    jobs:
      - build:
          name: x64
          rclass: medium
      - build:
          name: aarch64
          rclass: arm.medium
  # every week, run build too, in case packages got updated
  nightly:
    <<: *jobs
    triggers:
      - schedule:
          cron: "0 4 * * *"
          filters:
            branches:
              only:
                - master
